package com.example.gr.database.entities;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userAttributesDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig deviceAttributesDaoConfig;
    private final DaoConfig deviceDaoConfig;
    private final DaoConfig tagDaoConfig;
    private final DaoConfig activityDescriptionDaoConfig;
    private final DaoConfig activityDescTagLinkDaoConfig;
    private final DaoConfig miBandActivitySampleDaoConfig;
    private final DaoConfig huamiExtendedActivitySampleDaoConfig;
    private final DaoConfig huamiStressSampleDaoConfig;
    private final DaoConfig huamiSpo2SampleDaoConfig;
    private final DaoConfig huamiHeartRateManualSampleDaoConfig;
    private final DaoConfig huamiHeartRateMaxSampleDaoConfig;
    private final DaoConfig huamiHeartRateRestingSampleDaoConfig;
    private final DaoConfig huamiPaiSampleDaoConfig;
    private final DaoConfig huamiSleepRespiratoryRateSampleDaoConfig;
    private final DaoConfig calendarSyncStateDaoConfig;
    private final DaoConfig alarmDaoConfig;
    private final DaoConfig reminderDaoConfig;
    private final DaoConfig worldClockDaoConfig;
    private final DaoConfig contactDaoConfig;
    private final DaoConfig appSpecificNotificationSettingDaoConfig;
    private final DaoConfig notificationFilterDaoConfig;
    private final DaoConfig notificationFilterEntryDaoConfig;
    private final DaoConfig baseActivitySummaryDaoConfig;
    private final DaoConfig batteryLevelDaoConfig;

    private final UserAttributesDao userAttributesDao;
    private final UserDao userDao;
    private final DeviceAttributesDao deviceAttributesDao;
    private final DeviceDao deviceDao;
    private final TagDao tagDao;
    private final ActivityDescriptionDao activityDescriptionDao;
    private final ActivityDescTagLinkDao activityDescTagLinkDao;
    private final MiBandActivitySampleDao miBandActivitySampleDao;
    private final HuamiExtendedActivitySampleDao huamiExtendedActivitySampleDao;
    private final HuamiStressSampleDao huamiStressSampleDao;
    private final HuamiSpo2SampleDao huamiSpo2SampleDao;
    private final HuamiHeartRateManualSampleDao huamiHeartRateManualSampleDao;
    private final HuamiHeartRateMaxSampleDao huamiHeartRateMaxSampleDao;
    private final HuamiHeartRateRestingSampleDao huamiHeartRateRestingSampleDao;
    private final HuamiPaiSampleDao huamiPaiSampleDao;
    private final HuamiSleepRespiratoryRateSampleDao huamiSleepRespiratoryRateSampleDao;
    private final CalendarSyncStateDao calendarSyncStateDao;
    private final AlarmDao alarmDao;
    private final ReminderDao reminderDao;
    private final WorldClockDao worldClockDao;
    private final ContactDao contactDao;
    private final AppSpecificNotificationSettingDao appSpecificNotificationSettingDao;
    private final NotificationFilterDao notificationFilterDao;
    private final NotificationFilterEntryDao notificationFilterEntryDao;
    private final BaseActivitySummaryDao baseActivitySummaryDao;
    private final BatteryLevelDao batteryLevelDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userAttributesDaoConfig = daoConfigMap.get(UserAttributesDao.class).clone();
        userAttributesDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        deviceAttributesDaoConfig = daoConfigMap.get(DeviceAttributesDao.class).clone();
        deviceAttributesDaoConfig.initIdentityScope(type);

        deviceDaoConfig = daoConfigMap.get(DeviceDao.class).clone();
        deviceDaoConfig.initIdentityScope(type);

        tagDaoConfig = daoConfigMap.get(TagDao.class).clone();
        tagDaoConfig.initIdentityScope(type);

        activityDescriptionDaoConfig = daoConfigMap.get(ActivityDescriptionDao.class).clone();
        activityDescriptionDaoConfig.initIdentityScope(type);

        activityDescTagLinkDaoConfig = daoConfigMap.get(ActivityDescTagLinkDao.class).clone();
        activityDescTagLinkDaoConfig.initIdentityScope(type);

        miBandActivitySampleDaoConfig = daoConfigMap.get(MiBandActivitySampleDao.class).clone();
        miBandActivitySampleDaoConfig.initIdentityScope(type);

        huamiExtendedActivitySampleDaoConfig = daoConfigMap.get(HuamiExtendedActivitySampleDao.class).clone();
        huamiExtendedActivitySampleDaoConfig.initIdentityScope(type);

        huamiStressSampleDaoConfig = daoConfigMap.get(HuamiStressSampleDao.class).clone();
        huamiStressSampleDaoConfig.initIdentityScope(type);

        huamiSpo2SampleDaoConfig = daoConfigMap.get(HuamiSpo2SampleDao.class).clone();
        huamiSpo2SampleDaoConfig.initIdentityScope(type);

        huamiHeartRateManualSampleDaoConfig = daoConfigMap.get(HuamiHeartRateManualSampleDao.class).clone();
        huamiHeartRateManualSampleDaoConfig.initIdentityScope(type);

        huamiHeartRateMaxSampleDaoConfig = daoConfigMap.get(HuamiHeartRateMaxSampleDao.class).clone();
        huamiHeartRateMaxSampleDaoConfig.initIdentityScope(type);

        huamiHeartRateRestingSampleDaoConfig = daoConfigMap.get(HuamiHeartRateRestingSampleDao.class).clone();
        huamiHeartRateRestingSampleDaoConfig.initIdentityScope(type);

        huamiPaiSampleDaoConfig = daoConfigMap.get(HuamiPaiSampleDao.class).clone();
        huamiPaiSampleDaoConfig.initIdentityScope(type);

        huamiSleepRespiratoryRateSampleDaoConfig = daoConfigMap.get(HuamiSleepRespiratoryRateSampleDao.class).clone();
        huamiSleepRespiratoryRateSampleDaoConfig.initIdentityScope(type);

        calendarSyncStateDaoConfig = daoConfigMap.get(CalendarSyncStateDao.class).clone();
        calendarSyncStateDaoConfig.initIdentityScope(type);

        alarmDaoConfig = daoConfigMap.get(AlarmDao.class).clone();
        alarmDaoConfig.initIdentityScope(type);

        reminderDaoConfig = daoConfigMap.get(ReminderDao.class).clone();
        reminderDaoConfig.initIdentityScope(type);

        worldClockDaoConfig = daoConfigMap.get(WorldClockDao.class).clone();
        worldClockDaoConfig.initIdentityScope(type);

        contactDaoConfig = daoConfigMap.get(ContactDao.class).clone();
        contactDaoConfig.initIdentityScope(type);

        appSpecificNotificationSettingDaoConfig = daoConfigMap.get(AppSpecificNotificationSettingDao.class).clone();
        appSpecificNotificationSettingDaoConfig.initIdentityScope(type);

        notificationFilterDaoConfig = daoConfigMap.get(NotificationFilterDao.class).clone();
        notificationFilterDaoConfig.initIdentityScope(type);

        notificationFilterEntryDaoConfig = daoConfigMap.get(NotificationFilterEntryDao.class).clone();
        notificationFilterEntryDaoConfig.initIdentityScope(type);

        baseActivitySummaryDaoConfig = daoConfigMap.get(BaseActivitySummaryDao.class).clone();
        baseActivitySummaryDaoConfig.initIdentityScope(type);

        batteryLevelDaoConfig = daoConfigMap.get(BatteryLevelDao.class).clone();
        batteryLevelDaoConfig.initIdentityScope(type);

        userAttributesDao = new UserAttributesDao(userAttributesDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        deviceAttributesDao = new DeviceAttributesDao(deviceAttributesDaoConfig, this);
        deviceDao = new DeviceDao(deviceDaoConfig, this);
        tagDao = new TagDao(tagDaoConfig, this);
        activityDescriptionDao = new ActivityDescriptionDao(activityDescriptionDaoConfig, this);
        activityDescTagLinkDao = new ActivityDescTagLinkDao(activityDescTagLinkDaoConfig, this);
        miBandActivitySampleDao = new MiBandActivitySampleDao(miBandActivitySampleDaoConfig, this);
        huamiExtendedActivitySampleDao = new HuamiExtendedActivitySampleDao(huamiExtendedActivitySampleDaoConfig, this);
        huamiStressSampleDao = new HuamiStressSampleDao(huamiStressSampleDaoConfig, this);
        huamiSpo2SampleDao = new HuamiSpo2SampleDao(huamiSpo2SampleDaoConfig, this);
        huamiHeartRateManualSampleDao = new HuamiHeartRateManualSampleDao(huamiHeartRateManualSampleDaoConfig, this);
        huamiHeartRateMaxSampleDao = new HuamiHeartRateMaxSampleDao(huamiHeartRateMaxSampleDaoConfig, this);
        huamiHeartRateRestingSampleDao = new HuamiHeartRateRestingSampleDao(huamiHeartRateRestingSampleDaoConfig, this);
        huamiPaiSampleDao = new HuamiPaiSampleDao(huamiPaiSampleDaoConfig, this);
        huamiSleepRespiratoryRateSampleDao = new HuamiSleepRespiratoryRateSampleDao(huamiSleepRespiratoryRateSampleDaoConfig, this);
        calendarSyncStateDao = new CalendarSyncStateDao(calendarSyncStateDaoConfig, this);
        alarmDao = new AlarmDao(alarmDaoConfig, this);
        reminderDao = new ReminderDao(reminderDaoConfig, this);
        worldClockDao = new WorldClockDao(worldClockDaoConfig, this);
        contactDao = new ContactDao(contactDaoConfig, this);
        appSpecificNotificationSettingDao = new AppSpecificNotificationSettingDao(appSpecificNotificationSettingDaoConfig, this);
        notificationFilterDao = new NotificationFilterDao(notificationFilterDaoConfig, this);
        notificationFilterEntryDao = new NotificationFilterEntryDao(notificationFilterEntryDaoConfig, this);
        baseActivitySummaryDao = new BaseActivitySummaryDao(baseActivitySummaryDaoConfig, this);
        batteryLevelDao = new BatteryLevelDao(batteryLevelDaoConfig, this);

        registerDao(UserAttributes.class, userAttributesDao);
        registerDao(User.class, userDao);
        registerDao(DeviceAttributes.class, deviceAttributesDao);
        registerDao(Device.class, deviceDao);
        registerDao(Tag.class, tagDao);
        registerDao(ActivityDescription.class, activityDescriptionDao);
        registerDao(ActivityDescTagLink.class, activityDescTagLinkDao);
        registerDao(MiBandActivitySample.class, miBandActivitySampleDao);
        registerDao(HuamiExtendedActivitySample.class, huamiExtendedActivitySampleDao);
        registerDao(HuamiStressSample.class, huamiStressSampleDao);
        registerDao(HuamiSpo2Sample.class, huamiSpo2SampleDao);
        registerDao(HuamiHeartRateManualSample.class, huamiHeartRateManualSampleDao);
        registerDao(HuamiHeartRateMaxSample.class, huamiHeartRateMaxSampleDao);
        registerDao(HuamiHeartRateRestingSample.class, huamiHeartRateRestingSampleDao);
        registerDao(HuamiPaiSample.class, huamiPaiSampleDao);
        registerDao(HuamiSleepRespiratoryRateSample.class, huamiSleepRespiratoryRateSampleDao);
        registerDao(CalendarSyncState.class, calendarSyncStateDao);
        registerDao(Alarm.class, alarmDao);
        registerDao(Reminder.class, reminderDao);
        registerDao(WorldClock.class, worldClockDao);
        registerDao(Contact.class, contactDao);
        registerDao(AppSpecificNotificationSetting.class, appSpecificNotificationSettingDao);
        registerDao(NotificationFilter.class, notificationFilterDao);
        registerDao(NotificationFilterEntry.class, notificationFilterEntryDao);
        registerDao(BaseActivitySummary.class, baseActivitySummaryDao);
        registerDao(BatteryLevel.class, batteryLevelDao);
    }
    
    public void clear() {
        userAttributesDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
        deviceAttributesDaoConfig.getIdentityScope().clear();
        deviceDaoConfig.getIdentityScope().clear();
        tagDaoConfig.getIdentityScope().clear();
        activityDescriptionDaoConfig.getIdentityScope().clear();
        activityDescTagLinkDaoConfig.getIdentityScope().clear();
        miBandActivitySampleDaoConfig.getIdentityScope().clear();
        huamiExtendedActivitySampleDaoConfig.getIdentityScope().clear();
        huamiStressSampleDaoConfig.getIdentityScope().clear();
        huamiSpo2SampleDaoConfig.getIdentityScope().clear();
        huamiHeartRateManualSampleDaoConfig.getIdentityScope().clear();
        huamiHeartRateMaxSampleDaoConfig.getIdentityScope().clear();
        huamiHeartRateRestingSampleDaoConfig.getIdentityScope().clear();
        huamiPaiSampleDaoConfig.getIdentityScope().clear();
        huamiSleepRespiratoryRateSampleDaoConfig.getIdentityScope().clear();
        calendarSyncStateDaoConfig.getIdentityScope().clear();
        alarmDaoConfig.getIdentityScope().clear();
        reminderDaoConfig.getIdentityScope().clear();
        worldClockDaoConfig.getIdentityScope().clear();
        contactDaoConfig.getIdentityScope().clear();
        appSpecificNotificationSettingDaoConfig.getIdentityScope().clear();
        notificationFilterDaoConfig.getIdentityScope().clear();
        notificationFilterEntryDaoConfig.getIdentityScope().clear();
        baseActivitySummaryDaoConfig.getIdentityScope().clear();
        batteryLevelDaoConfig.getIdentityScope().clear();
    }

    public UserAttributesDao getUserAttributesDao() {
        return userAttributesDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public DeviceAttributesDao getDeviceAttributesDao() {
        return deviceAttributesDao;
    }

    public DeviceDao getDeviceDao() {
        return deviceDao;
    }

    public TagDao getTagDao() {
        return tagDao;
    }

    public ActivityDescriptionDao getActivityDescriptionDao() {
        return activityDescriptionDao;
    }

    public ActivityDescTagLinkDao getActivityDescTagLinkDao() {
        return activityDescTagLinkDao;
    }

    public MiBandActivitySampleDao getMiBandActivitySampleDao() {
        return miBandActivitySampleDao;
    }

    public HuamiExtendedActivitySampleDao getHuamiExtendedActivitySampleDao() {
        return huamiExtendedActivitySampleDao;
    }

    public HuamiStressSampleDao getHuamiStressSampleDao() {
        return huamiStressSampleDao;
    }

    public HuamiSpo2SampleDao getHuamiSpo2SampleDao() {
        return huamiSpo2SampleDao;
    }

    public HuamiHeartRateManualSampleDao getHuamiHeartRateManualSampleDao() {
        return huamiHeartRateManualSampleDao;
    }

    public HuamiHeartRateMaxSampleDao getHuamiHeartRateMaxSampleDao() {
        return huamiHeartRateMaxSampleDao;
    }

    public HuamiHeartRateRestingSampleDao getHuamiHeartRateRestingSampleDao() {
        return huamiHeartRateRestingSampleDao;
    }

    public HuamiPaiSampleDao getHuamiPaiSampleDao() {
        return huamiPaiSampleDao;
    }

    public HuamiSleepRespiratoryRateSampleDao getHuamiSleepRespiratoryRateSampleDao() {
        return huamiSleepRespiratoryRateSampleDao;
    }

    public CalendarSyncStateDao getCalendarSyncStateDao() {
        return calendarSyncStateDao;
    }

    public AlarmDao getAlarmDao() {
        return alarmDao;
    }

    public ReminderDao getReminderDao() {
        return reminderDao;
    }

    public WorldClockDao getWorldClockDao() {
        return worldClockDao;
    }

    public ContactDao getContactDao() {
        return contactDao;
    }

    public AppSpecificNotificationSettingDao getAppSpecificNotificationSettingDao() {
        return appSpecificNotificationSettingDao;
    }

    public NotificationFilterDao getNotificationFilterDao() {
        return notificationFilterDao;
    }

    public NotificationFilterEntryDao getNotificationFilterEntryDao() {
        return notificationFilterEntryDao;
    }

    public BaseActivitySummaryDao getBaseActivitySummaryDao() {
        return baseActivitySummaryDao;
    }

    public BatteryLevelDao getBatteryLevelDao() {
        return batteryLevelDao;
    }

}
